services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
    restart: unless-stopped
    container_name: zabbix
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
    restart: unless-stopped
    container_name: zabbix-nginx
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server

  zabbix-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_password
    container_name: database-zabbix
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - zabbix-db-storage:/var/lib/postgresql/data
      - /var/lib/postgresql/data/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    restart: unless-stopped
    container_name: grafana
    volumes:
      - /var/lib/grafana/plugins:/var/lib/grafana/plugins

volumes:
  zabbix-db-storage:
